{% set version = "1.1.19" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-idpmisc
  version: {{ version|replace("-", "_") }}

source:
  fn: IDPmisc_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/IDPmisc_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/IDPmisc/IDPmisc_{{ version }}.tar.gz
  sha256: 0d5e35252c7ec2654a3d64949bdc0977cc8479f8ada97bccd0d90d70aadb0c8f

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-lattice >=0.19_26

  run:
    - r-base
    - r-lattice >=0.19_26

test:
  commands:
    - $R -e "library('IDPmisc')"  # [not win]
    - "\"%R%\" -e \"library('IDPmisc')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=IDPmisc
  license: GPL (>= 3)
  summary: |
    The IDPmisc package contains different high-level graphics functions for displaying
    large datasets, displaying circular data in a very flexible way, finding local maxima,
    brewing color ramps, drawing nice arrows, zooming 2D-plots, creating figures with
    differently colored margin and plot region.  In addition, the package contains auxiliary
    functions for data manipulation like omitting observations with irregular values
    or selecting data by logical vectors, which include NAs. Other functions are especially
    useful in spectroscopy and analyses of environmental data: robust baseline fitting,
    finding peaks in spectra.
  license_family: GPL3

extra:
  recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
