# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "MjIilxTTKYVx13yNR5gRtejlLdo9NM5KWpl03gSpqpyJz7SPmNT+ujiZMhxZIRwvO9ppFyBTdqcAcFdnvWZt3ZSX9//8LGr0mmXoiu61+Ry6iOPDS+wyPZ9puACv2qfIEJMBY2hcjC8Vfn64IDZU0SZ+CTT5m3eQ00OM5QINpOFmoMwQlSa6bHkcBppUkzv58OmP6Y2qKTlXXWxqajUeqgF8k45KlIvivEfOGUuz1BMwFv52X70GvhydQHsz+JzG8gIMG24TJ5O7QVGVaP0++5CY/PdlP0bfPQSBmKWyhpvW7eHHAEpT8MEEgs0dEZXUeke3pc7JoanIoK/dqwp1zUpbCVc++jQTiapxMBa+/ySpJCfhmvhF8+ZVgtJnwjfMhexuFsG2/HMzUqtAGAQ4NKH1EIjAe5/rlQfWlkU9914LaRyLg/ChaQ/e3w+WYkHnla0OH77R25/PO0C57M6gBN4kil1TtVrX3LxWC77LDtIuKbbH6EDBYENpJI8CpQL5OoM3yYsT98dvGRMFncb0urt+TP9Lu0+oOf0Ju1RMHk5JDUOX4tOTC3ao/KongPblg8UEBWsT+mKZyNprTTKnErAa1KZzIufW4i2Ow0ulAIVIFgCOCfZWViNhungNixWO0qHCIIN1KS/Fgcz3T8HVlqQ2gvdslFPh1dnm+/noLoo="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
